//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bt
{
    using System;
    using System.Collections.Generic;
    
    public partial class binhluan
    {
        public int id_bl { get; set; }
        public Nullable<int> masp { get; set; }
        public string ten { get; set; }
        public string sdt { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public string noidung { get; set; }
    
        public virtual sanpham sanpham { get; set; }
    }
}
