//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bt
{
    using System;
    using System.Collections.Generic;
    
    public partial class cthdnhap
    {
        public int id_cthdnhap { get; set; }
        public Nullable<int> id_hdnhap { get; set; }
        public Nullable<int> masp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> dongia { get; set; }
    
        public virtual hdn hdn { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
